In [ ]:

import pandas as pd
import numpy as np
df = pd.read_csv('/content/weather_classification_data.csv')
print(df.head())

   Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
0         14.0        73         9.5               82.0  partly cloudy   
1         39.0        96         8.5               71.0  partly cloudy   
2         30.0        64         7.0               16.0          clear   
3         38.0        83         1.5               82.0          clear   
4         27.0        74        17.0               66.0       overcast   

   Atmospheric Pressure  UV Index  Season  Visibility (km)  Location  \
0               1010.82         2  Winter              3.5    inland   
1               1011.43         7  Spring             10.0    inland   
2               1018.72         5  Spring              5.5  mountain   
3               1026.25         7  Spring              1.0   coastal   
4                990.67         1  Winter              2.5  mountain   

  Weather Type  
0        Rainy  
1       Cloudy  
2        Sunny  
3        Sunny  
4        Rainy  


In [ ]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_data = numeric_df.to_numpy()
print(numeric_data)

[[  14.     73.      9.5  ... 1010.82    2.      3.5 ]
 [  39.     96.      8.5  ... 1011.43    7.     10.  ]
 [  30.     64.      7.   ... 1018.72    5.      5.5 ]
 ...
 [  30.     77.      5.5  ... 1012.69    3.      9.  ]
 [   3.     76.     10.   ...  984.27    0.      2.  ]
 [  -5.     38.      0.   ... 1015.37    5.     10.  ]]


In [ ]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
range_arr = np.arange(10)
print(numeric_data[0])     # First row
print(numeric_data[0, 1])  # Element at row 0, column 1


[  14.     73.      9.5    82.   1010.82    2.      3.5 ]
73.0


In [ ]:
print(numeric_data[0:5, :3])  # First 5 rows, first 3 columns


[[14.  73.   9.5]
 [39.  96.   8.5]
 [30.  64.   7. ]
 [38.  83.   1.5]
 [27.  74.  17. ]]


In [ ]:
reshaped = numeric_data[:12].reshape(4, -1)  # Reshape first 12 elements into 4 rows
print(reshaped)

[[ 1.40000e+01  7.30000e+01  9.50000e+00  8.20000e+01  1.01082e+03
   2.00000e+00  3.50000e+00  3.90000e+01  9.60000e+01  8.50000e+00
   7.10000e+01  1.01143e+03  7.00000e+00  1.00000e+01  3.00000e+01
   6.40000e+01  7.00000e+00  1.60000e+01  1.01872e+03  5.00000e+00
   5.50000e+00]
 [ 3.80000e+01  8.30000e+01  1.50000e+00  8.20000e+01  1.02625e+03
   7.00000e+00  1.00000e+00  2.70000e+01  7.40000e+01  1.70000e+01
   6.60000e+01  9.90670e+02  1.00000e+00  2.50000e+00  3.20000e+01
   5.50000e+01  3.50000e+00  2.60000e+01  1.01003e+03  2.00000e+00
   5.00000e+00]
 [-2.00000e+00  9.70000e+01  8.00000e+00  8.60000e+01  9.90870e+02
   1.00000e+00  4.00000e+00  3.00000e+00  8.50000e+01  6.00000e+00
   9.60000e+01  9.84460e+02  1.00000e+00  3.50000e+00  3.00000e+00
   8.30000e+01  6.00000e+00  6.60000e+01  9.99440e+02  0.00000e+00
   1.00000e+00]
 [ 2.80000e+01  7.40000e+01  8.50000e+00  1.07000e+02  1.01213e+03
   8.00000e+00  7.50000e+00  3.50000e+01  4.50000e+01  6.00000e+00
   8.60000e+01

In [ ]:
a, b = np.split(numeric_data, 2)  # Split into two halves
concat = np.concatenate([a, b])   # Combine back
print(concat)

[[  14.     73.      9.5  ... 1010.82    2.      3.5 ]
 [  39.     96.      8.5  ... 1011.43    7.     10.  ]
 [  30.     64.      7.   ... 1018.72    5.      5.5 ]
 ...
 [  30.     77.      5.5  ... 1012.69    3.      9.  ]
 [   3.     76.     10.   ...  984.27    0.      2.  ]
 [  -5.     38.      0.   ... 1015.37    5.     10.  ]]


In [ ]:
squared = np.square(numeric_data)
sine = np.sin(numeric_data[:, 0])  # Apply on Temperature
print(squared)
print(sine)

[[1.96000000e+02 5.32900000e+03 9.02500000e+01 ... 1.02175707e+06
  4.00000000e+00 1.22500000e+01]
 [1.52100000e+03 9.21600000e+03 7.22500000e+01 ... 1.02299064e+06
  4.90000000e+01 1.00000000e+02]
 [9.00000000e+02 4.09600000e+03 4.90000000e+01 ... 1.03779044e+06
  2.50000000e+01 3.02500000e+01]
 ...
 [9.00000000e+02 5.92900000e+03 3.02500000e+01 ... 1.02554104e+06
  9.00000000e+00 8.10000000e+01]
 [9.00000000e+00 5.77600000e+03 1.00000000e+02 ... 9.68787433e+05
  0.00000000e+00 4.00000000e+00]
 [2.50000000e+01 1.44400000e+03 0.00000000e+00 ... 1.03097624e+06
  2.50000000e+01 1.00000000e+02]]
[ 0.99060736  0.96379539 -0.98803162 ... -0.98803162  0.14112001
  0.95892427]


In [ ]:
mean = np.mean(numeric_data, axis=0)
sum_ = np.sum(numeric_data, axis=0)
std_dev = np.std(numeric_data, axis=0)
print(mean)
print(sum)
print(std_dev)

[  19.12757576   68.71083333    9.83219697   53.64439394 1005.82789621
    4.00575758    5.46291667]
<built-in function sum>
[17.385668   20.19348314  6.90844244 31.94533065 37.1981796   3.85645428
  3.3713712 ]


In [ ]:
broadcast_result = numeric_data + 5  # Adds 5 to every element
print(broadcast_result)

[[  19.     78.     14.5  ... 1015.82    7.      8.5 ]
 [  44.    101.     13.5  ... 1016.43   12.     15.  ]
 [  35.     69.     12.   ... 1023.72   10.     10.5 ]
 ...
 [  35.     82.     10.5  ... 1017.69    8.     14.  ]
 [   8.     81.     15.   ...  989.27    5.      7.  ]
 [   0.     43.      5.   ... 1020.37   10.     15.  ]]


In [ ]:
hot_days = numeric_data[:, 0] > 30  # Temperature > 30
print(numeric_data[hot_days])      # Filter rows with high temperature


[[3.90000e+01 9.60000e+01 8.50000e+00 ... 1.01143e+03 7.00000e+00
  1.00000e+01]
 [3.80000e+01 8.30000e+01 1.50000e+00 ... 1.02625e+03 7.00000e+00
  1.00000e+00]
 [3.20000e+01 5.50000e+01 3.50000e+00 ... 1.01003e+03 2.00000e+00
  5.00000e+00]
 ...
 [3.30000e+01 5.40000e+01 5.00000e-01 ... 1.01266e+03 7.00000e+00
  9.00000e+00]
 [3.70000e+01 1.06000e+02 2.35000e+01 ... 9.98710e+02 1.40000e+01
  3.00000e+00]
 [3.10000e+01 2.40000e+01 8.00000e+00 ... 1.02961e+03 8.00000e+00
  9.00000e+00]]


In [ ]:
row_indices = [0, 10, 100]
fancy_rows = numeric_data[row_indices]
print(fancy_rows)

[[1.40000e+01 7.30000e+01 9.50000e+00 8.20000e+01 1.01082e+03 2.00000e+00
  3.50000e+00]
 [3.50000e+01 4.50000e+01 6.00000e+00 8.60000e+01 8.79880e+02 2.00000e+00
  1.00000e+00]
 [4.00000e+01 6.60000e+01 8.00000e+00 5.00000e+00 1.01982e+03 5.00000e+00
  5.50000e+00]]


In [ ]:
sorted_temp = np.sort(numeric_data[:, 0])     # Sort Temperature
sorted_indices = np.argsort(numeric_data[:, 0])  # Indices that sort Temperature
print(sorted_indices)
print(sorted_temp)

[ 4609  8059   267 ...  2958 10993  5085]
[-25. -24. -24. ... 107. 108. 109.]


In [ ]:
top_5_wind = np.partition(numeric_data[:, 2], -5)[-5:]  # Top 5 wind speeds
print(top_5_wind)

[47.  47.  47.  47.5 48.5]


In [ ]:
structured = np.array(
    [(x[0], x[1]) for x in numeric_data],
    dtype=[('Temperature', 'f8'), ('Humidity', 'i4')]
)
print(structured[:3])


[(14., 73) (39., 96) (30., 64)]
